.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils Directory Reference" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarray_test\&.c\fP"
.br
.ti -1c
.RI "file \fBcolors\&.c\fP"
.br
.ti -1c
.RI "file \fBcolors_test\&.c\fP"
.br
.ti -1c
.RI "file \fBcommand_line\&.c\fP"
.br
.ti -1c
.RI "file \fBcommand_line_test\&.c\fP"
.br
.ti -1c
.RI "file \fBerrors\&.c\fP"
.br
.ti -1c
.RI "file \fBerrors_test\&.c\fP"
.br
.ti -1c
.RI "file \fBlogger\&.c\fP"
.br
.RI "a thread safe logger with optional printf style logging "
.ti -1c
.RI "file \fBlogger_test\&.c\fP"
.br
.ti -1c
.RI "file \fBrandom\&.c\fP"
.br
.ti -1c
.RI "file \fBrandom_test\&.c\fP"
.br
.ti -1c
.RI "file \fBreturns\&.c\fP"
.br
.ti -1c
.RI "file \fBreturns_test\&.c\fP"
.br
.ti -1c
.RI "file \fBsafe_math\&.c\fP"
.br
.ti -1c
.RI "file \fBsafe_math_test\&.c\fP"
.br
.ti -1c
.RI "file \fBsafe_mem\&.c\fP"
.br
.ti -1c
.RI "file \fBsafe_mem_test\&.c\fP"
.br
.in -1c
