.TH "/media/solidity/DATA/Code/bonedaddy/c-template/include Directory Reference" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBnetwork\fP"
.br
.ti -1c
.RI "directory \fBsync\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
