.TH "/media/solidity/DATA/Code/bonedaddy/c-template/include/network/socket Directory Reference" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/include/network/socket Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsocket\&.h\fP"
.br
.RI "TCP socket servers, clients, and tooling for working with sockets\&. "
.ti -1c
.RI "file \fBsocket_server\&.h\fP"
.br
.RI "TCP socket servers, clients, and tooling for working with sockets\&. "
.in -1c
