.TH "/media/solidity/DATA/Code/bonedaddy/c-template/include/sync Directory Reference" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/include/sync Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwait_group\&.h\fP"
.br
.RI "provides C equivalent of Golang sync\&.Wait enables 'signalling' multiple threads allows management of multiple threads, and enabling clean exits or cleanups it is a bit different than joining pthreads to wait for processes to exit as it doesn't require attached pthreads (can be used with detached) for synchronizatiion "
.in -1c
