.TH "an" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
an \- callback is a function to be executed  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
callback is a function to be executed 

to run 

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
