.TH "/media/solidity/DATA/Code/bonedaddy/c-template/include/utils/array_len.h" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/include/utils/array_len.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBarray_len\fP(x)   ((\fBarray_size\fP(x) > 0) ? sizeof(x) / sizeof(x[0]) : 0)"
.br
.ti -1c
.RI "#define \fBarray_size\fP(x)   (sizeof(x))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define array_len(x)   ((\fBarray_size\fP(x) > 0) ? sizeof(x) / sizeof(x[0]) : 0)"

.PP
Definition at line 2 of file array_len\&.h\&.
.SS "#define array_size(x)   (sizeof(x))"

.PP
Definition at line 4 of file array_len\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
