.TH "cg_error" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cg_error
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <errors\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file errors\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* cg_error::message"

.PP
Definition at line 15 of file errors\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
