.TH "cg_return" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cg_return \- allows returning both a value and error message from a function call useful as it makes it easier to provid better error message and handling similar to go  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <returns\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "\fBcg_error\fP * \fBerr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
allows returning both a value and error message from a function call useful as it makes it easier to provid better error message and handling similar to go 
.PP
Definition at line 14 of file returns\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcg_error\fP* cg_return::err"

.PP
Definition at line 19 of file returns\&.h\&.
.SS "void* cg_return::value"

.PP
Definition at line 16 of file returns\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
