.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/colors_test.c" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/colors_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/colors\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBargs\fP"
.br
.ti -1c
.RI "struct \fBtest\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBargs\fP \fBargs\fP"
.br
.ti -1c
.RI "typedef struct \fBtest\fP \fBtest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_print_color\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_get_ansi_color_scheme\fP (void **state)"
.br
.ti -1c
.RI "void \fBvalidate_test_args\fP (\fBtest\fP testdata)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBargs\fP \fBargs\fP"

.SS "typedef struct \fBtest\fP \fBtest\fP"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 103 of file colors_test\&.c\&.
.SS "void test_get_ansi_color_scheme (void ** state)"

.PP
Definition at line 38 of file colors_test\&.c\&.
.SS "void test_print_color (void ** state)"

.SS "void validate_test_args (\fBtest\fP testdata)"

.PP
Definition at line 26 of file colors_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
