.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/command_line_test.c" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/command_line_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'command_line\&.c'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_hello_world\fP ()"
.br
.ti -1c
.RI "\fBcommand_handler\fP * \fBnew_test_command\fP ()"
.br
.ti -1c
.RI "void \fBtest_new_command_object\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_load_command\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_execute\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 80 of file command_line_test\&.c\&.
.SS "\fBcommand_handler\fP * new_test_command ()"

.PP
Definition at line 15 of file command_line_test\&.c\&.
.SS "void print_hello_world ()"

.PP
Definition at line 11 of file command_line_test\&.c\&.
.SS "void test_execute (void ** state)"

.PP
Definition at line 65 of file command_line_test\&.c\&.
.SS "void test_load_command (void ** state)"

.PP
Definition at line 46 of file command_line_test\&.c\&.
.SS "void test_new_command_object (void ** state)"

.PP
Definition at line 28 of file command_line_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
