.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/random.c" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/random.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/random\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/errors\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/returns\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcg_return\fP * \fBget_random_string\fP (int stringLength)"
.br
.ti -1c
.RI "int \fBget_random_number\fP (int lower, int upper)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int get_random_number (int lower, int upper)"

.PP
Definition at line 22 of file random\&.c\&.
.SS "\fBcg_return\fP* get_random_string (int stringLength)"

.PP
Definition at line 7 of file random\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
