.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/random_test.c" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/random_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/random\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/array_len\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/returns\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_get_random_string_length\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_get_random_number_range\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 32 of file random_test\&.c\&.
.SS "void test_get_random_number_range (void ** state)"

.PP
Definition at line 27 of file random_test\&.c\&.
.SS "void test_get_random_string_length (void ** state)"

.PP
Definition at line 15 of file random_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
