.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/returns.c" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/returns.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/errors\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/returns\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcg_return\fP * \fBnew_cg_return\fP (void *value, \fBcg_error\fP *err)"
.br
.RI "creates a new \fBcg_return\fP struct "
.ti -1c
.RI "void \fBfree_cg_return\fP (\fBcg_return\fP *ret)"
.br
.RI "frees up resources associated with an instance of \fBcg_return\fP "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void free_cg_return (\fBcg_return\fP * ret)"

.PP
frees up resources associated with an instance of \fBcg_return\fP 
.PP
Definition at line 24 of file returns\&.c\&.
.SS "\fBcg_return\fP* new_cg_return (void * value, \fBcg_error\fP * err)"

.PP
creates a new \fBcg_return\fP struct 
.PP
Definition at line 5 of file returns\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
