.TH "/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/safe_mem_test.c" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/c-template/src/utils/safe_mem_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./include/utils/safe_mem\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtest_data\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtest_data\fP \fBtest_data\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_new_memory_object_null\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_new_memory_object_test_data\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBtest_data\fP \fBtest_data\fP"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 57 of file safe_mem_test\&.c\&.
.SS "void test_new_memory_object_null (void ** state)"

.PP
Definition at line 18 of file safe_mem_test\&.c\&.
.SS "void test_new_memory_object_test_data (void ** state)"

.PP
Definition at line 37 of file safe_mem_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
