.TH "test_data" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBc\fP [100]"
.br
.ti -1c
.RI "bool \fBb\fP [100]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file safe_mem_test\&.c\&.
.SH "Field Documentation"
.PP 
.SS "bool test_data::b[100]"

.PP
Definition at line 12 of file safe_mem_test\&.c\&.
.SS "char test_data::c[100]"

.PP
Definition at line 11 of file safe_mem_test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
