.TH "test" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBargs\fP \fBargs\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file colors_test\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBargs\fP test::args"

.PP
Definition at line 17 of file colors_test\&.c\&.
.SS "char* test::name"

.PP
Definition at line 18 of file colors_test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
