.TH "the" 3 "Thu Jul 9 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
the \- contains the list of possible commands to execute  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
contains the list of possible commands to execute 

object 

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
